### ISSUE TITLE
Hashed Samples

### ISSUE THREAD

**Issue by dylanmr** [wmacnair/SampleQC#22]
Hi WIll, 

Thanks for the cool package, really excited to try this on my data! 

If working with hashed data, would you suggest filtering out doublets and negatives prior to runnning sampleqc? Or would you classify all cells based on HTO data and then run sampleqc using all cells?

Thanks!
Dylan

**Comment by wmacnair** [comment]
Hey Dylan, thanks for your interest!

I'm not so familiar with multiplexed samples and their effects on data myself, but a quick look suggests that yes, you should exclude doublets and negatives first. Please correct me if I've misunderstood this, but I think:
- Negatives would in any case be low quality cells with e.g. low counts.
- The ordering "remove doublets then do QC" rather than "do QC then remove doublets" makes more sense because "QC first" then makes it harder to identify doublets. Doublets also introduce a slight distortion to the QC metric distributions, so `SampleQC` works slightly better with them removed.

For a bit more detail, this is what I wrote in the pre-print:

> Prior to running SampleQC, we recommend excluding empty droplets, for example by running emptyDrops with either the default or a more generous cutoff, to ensure that all genuine cells are included. This may result in some empty droplets being used as input to SampleQC, but they should be identified as outlier cells and later excluded.

> We then recommend removing multiplets before running SampleQC for two principal reasons. Firstly, excluding low quality cells first assumes that all doublets are composed of two good quality cells; by excluding low quality cells first, it is then more difficult to detect doublets comprising one good quality and one low quality cell. Secondly, just as the count vectors for doublets are linear combinations of two true cells, their QC metric values are also functions of combinations of two true cells.  The practical impact of this is that doublets introduce a small amount of noise to the QC metric distributions; excluding them results in cleaner distributions that are slightly easier for SampleQC to fit. (In addition, the number of cells used in the run is needed to accurately estimate the expected number of doublets. Excluding low quality cells first would distort this calculation; although this can be addressed by recording the initial number of cells.)

(Here I can also plug [scDblFinder](https://github.com/plger/scDblFinder) for your doublet needs, a nice package put together by @plger. With hashing, my understanding is that you can remove doublets from two different _samples_, but not two different cell _types_ from the same sample. `scDblFinder` is good at doing that 🙂 )

Hope this is helpful, and let me know if you have any more questions.

Will

**Comment by dylanmr** [comment]
Hi Will, 

Thanks for the quick answer! I cant believe i missed that section in the paper, clearly got too excited and tried to jump right into the vignette 😄  I have been using scDblFinder already and find it to be a great tool to compliment the standard hash demultiplexing!  

Thanks again, and ill close this topic for now

**Comment by wmacnair** [comment]
No problem, I know it's slightly hidden in the paper...

Drop me a line if you have any feedback on the vignette. I have a full-time non-academic job now, so I didn't have as much time as I'd have liked to do documentation and examples, but hopefully it covers the important things.

Cheers
Will
