### ISSUE TITLE
calc_pairwise_mmds

### ISSUE THREAD

**Issue by ardecasien** [wmacnair/SampleQC#24]
I receive the following error when running calc_pairwise_mmds - can you please assist?
- my input is two single cell RNAseq samples prepared with qc_dt
- qc_names = c('log_counts', 'log_feats', 'logit_mito')
- annots_disc = NULL
- annots_cont = NULL

sample-level parts of SampleQC:
  calculating 1 sample-sample MMDs:
  |=========================================================================================| 100%

Error in (function (edges, n = max(edges), directed = TRUE)  : 
  At type_indexededgelist.c:117 : cannot create empty graph with negative number of vertices, Invalid value

**Comment by lazappi** [comment]
I came across this error as well. I think it happens because it tries to calculate a nearest neighbour graph with at 5 nearest neighbour and if you have fewer samples than this it breaks. I think the functions are still useful with only one sample so if would be great if this worked.

**Comment by wmacnair** [comment]
Hi @ardecasien @lazappi 

Apologies that this has taken a while, turns out working on academic projects while having a non-academic job is tricky...

I thought I had fixed this before (with the parameter `one_group_only`) but I had not been thorough enough. I have now fixed it properly, and added a couple of additional tests to check it. 

One additional comment I have is that the use case driving `SampleQC` is really when you have a large number of samples. It should work fine for medium numbers, but I haven't really tried using it for smaller numbers.

Please let me know if you have any further issues!

Will
